name: Download SBOM

on:
  workflow_dispatch:

jobs:
  download-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate with GitHub CLI
      run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

    - name: Set timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV


    - name: Use GitHub CLI command
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sbom="$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/dependency-graph/sbom)"

        echo "sbom:$sbom" >> sbom.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact-sbom-${{ env.TIMESTAMP }}
        path: |
          sbom.json
        if-no-files-found: error
      
